spring.application.name=ai-chat-assistant
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.project-id=your-gcp-project-id
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
#spring.ai.google.genai.embedding.text.options.model=text-embedding-004
conversation.summary.threshold=4
conversation.summary.keep-recent-messages=2

spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.model.embedding.text=google-genai
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.profiles.active=dev
conversation.ttl=30m
spring.ai.google.genai.location=us-central1


spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-name=public

logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol=DEBUG



rag.documents-location=classpath:/docs/*.pdf
rag.chunk-size=800
rag.min-chunk-size-chars=350
rag.min-chunk-length-to-embed=5
rag.max-num-chunks=10000
rag.keep-separator=true
rag.top-k=5
rag.similarity-threshold=0.75

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_chat
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration (Optional)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.include=mcp,dev
logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=enterprise-ai-assistant

####################################################
# JWT
####################################################

security.jwt.secret=ThisIsMyVerySecretKeyForEnterpriseAIAssistant2026
security.jwt.expiration=3600000