####################################################
# MCP CLIENT
####################################################

spring.ai.mcp.client.enabled=false
spring.ai.mcp.client.name=ai-chat-assistant
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.toolcallback.enabled=true

####################################################
# Enterprise MCP Server
####################################################

spring.ai.mcp.client.streamable-http.connections.enterprise.url=http://127.0.0.1:8081
spring.ai.mcp.client.streamable-http.connections.enterprise.endpoint=/mcp