####################################################
# PostgreSQL
####################################################

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_chat
spring.datasource.username=postgres
spring.datasource.password=postgres

####################################################
# Redis
####################################################

spring.data.redis.host=localhost
spring.data.redis.port=6379

####################################################
# Ollama
####################################################

spring.ai.ollama.base-url=http://localhost:11434